#!/usr/bin/env bash
# ============================================================
# deploy_contract.sh
# Builds, optimises, and deploys the Soroban marketplace
# contract to Stellar Testnet.
# Requires: fund_account.sh to have been run first.
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$SCRIPT_DIR/.env.deploy"
CONTRACT_DIR="$REPO_ROOT/contracts/soroban-marketplace"
WASM_LOCAL="$CONTRACT_DIR/target/wasm32v1-none/release/soroban_marketplace.wasm"
WASM_WORKSPACE="$REPO_ROOT/target/wasm32v1-none/release/soroban_marketplace.wasm"
WASM="$WASM_WORKSPACE"
FRONTEND_ENV="$REPO_ROOT/frontend/afristore-app/.env.local"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Afristore — Deploy Soroban Contract to Testnet"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Check prerequisities ─────────────────────────────────────
for cmd in stellar cargo jq; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: '$cmd' is not installed."
    exit 1
  fi
done

if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: $ENV_FILE not found. Run ./fund_account.sh first."
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

# ── Build WASM ────────────────────────────────────────────────
echo ""
echo "Step 1/4  Building contract WASM..."
cd "$CONTRACT_DIR"
cargo build --target wasm32v1-none --release 2>&1

if [[ -f "$WASM_WORKSPACE" ]]; then
  WASM="$WASM_WORKSPACE"
elif [[ -f "$WASM_LOCAL" ]]; then
  WASM="$WASM_LOCAL"
else
  echo "ERROR: Built WASM not found in expected locations:"
  echo "  - $WASM_WORKSPACE"
  echo "  - $WASM_LOCAL"
  exit 1
fi

# ── Optimise WASM ─────────────────────────────────────────────
echo ""
echo "Step 2/4  Optimising WASM..."
if stellar contract optimize \
  --wasm "$WASM" \
  --wasm-out "$WASM"; then
  WASM_SIZE=$(wc -c <"$WASM")
  echo "  WASM size: ${WASM_SIZE} bytes"
else
  echo "  WARNING: WASM optimization failed. Continuing with unoptimized WASM."
fi

# ── Upload WASM to network ────────────────────────────────────
echo ""
echo "Step 3/4  Uploading WASM to ${NETWORK}..."
  output=$(stellar contract upload \
  --wasm "$WASM" \
  --source "$STELLAR_SECRET" \
  --rpc-url "$RPC_URL" \
  --network-passphrase "Test SDF Network ; September 2015" \
  --ignore-checks 2>&1) || { echo "$output" >&2; exit 1; }
WASM_HASH=$(echo "$output" | tail -1)
echo "  WASM hash: $WASM_HASH"

# ── Deploy contract instance ──────────────────────────────────
echo ""
echo "Step 4/4  Deploying contract instance..."
  output=$(stellar contract deploy \
  --wasm-hash "$WASM_HASH" \
  --source "$STELLAR_SECRET" \
  --rpc-url "$RPC_URL" \
  --network-passphrase "Test SDF Network ; September 2015" \
  --ignore-checks 2>&1) || { echo "$output" >&2; exit 1; }
CONTRACT_ID=$(echo "$output" | tail -1)
echo "  Contract ID: $CONTRACT_ID"

# ── Write frontend .env.local ────────────────────────────────
mkdir -p "$(dirname "$FRONTEND_ENV")"

update_env() {
  local key=$1
  local val=$2
  if grep -q "^${key}=" "$FRONTEND_ENV"; then
    sed "s|^${key}=.*|${key}=${val}|" "$FRONTEND_ENV" > "$FRONTEND_ENV.tmp"
    mv "$FRONTEND_ENV.tmp" "$FRONTEND_ENV"
  else
    echo "${key}=${val}" >> "$FRONTEND_ENV"
  fi
}

if [ ! -f "$FRONTEND_ENV" ]; then
  cat > "$FRONTEND_ENV" <<EOF
# Afristore Frontend — generated by deploy_contract.sh
NEXT_PUBLIC_CONTRACT_ID=$CONTRACT_ID
NEXT_PUBLIC_STELLAR_NETWORK=testnet
NEXT_PUBLIC_STELLAR_RPC_URL=$RPC_URL
NEXT_PUBLIC_STELLAR_HORIZON_URL=$HORIZON_URL
NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE=Test SDF Network ; September 2015

# Pinata IPFS — fill these in manually
PINATA_JWT=
NEXT_PUBLIC_PINATA_GATEWAY=https://gateway.pinata.cloud
EOF
else
  update_env "NEXT_PUBLIC_CONTRACT_ID" "$CONTRACT_ID"
  update_env "NEXT_PUBLIC_STELLAR_NETWORK" "testnet"
  update_env "NEXT_PUBLIC_STELLAR_RPC_URL" "$RPC_URL"
  update_env "NEXT_PUBLIC_STELLAR_HORIZON_URL" "$HORIZON_URL"
  update_env "NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE" "Test SDF Network ; September 2015"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✓ Deployment complete!"
echo ""
echo "  Contract ID : $CONTRACT_ID"
echo "  Network     : $NETWORK"
echo ""
echo "  Frontend env written to: $FRONTEND_ENV"
echo "  Add your PINATA_JWT to that file, then:"
echo "    cd frontend/afristore-app && npm install && npm run dev"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
